### ISSUE TITLE
Refactorisation: add protocol for DB access as implement Prisma and In-memory versions

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastagencyapi#9]
- [x] Sync -> get default, set_default
- [x] Gap between method in base
- [x] Rename to BackendDBProtocol and FrontendDBProtocol
- [x] Separate tests for prisma.py
- [x] Separate implementation of in memory
- [x] Separate tests for inmemory
- [x] Use inmemory in tests
- [x] class defaultdb
- [x] Remove typeadapter
- [x] fix agents/base.py
- [x] Move lifespan
- [x] Use Union[str, UUID]
- [x] Fix exception raising

**Comment by kumaranvpl** [comment]
Fixed at https://github.com/airtai/fastagencyapi/pull/6
